#!/bin/bash
source variables.cfg


#boostrap first consul
eval $(docker-machine env swarm-1)
docker run -d --net=host --cap-add=NET_ADMIN --privileged --name=consul \
  -e 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' \
  -e CONSUL=consul -e CONSUL_CHECK_LEADER=true \
  consul agent -server -bind=$(docker-machine ip swarm-1) \
    -client=0.0.0.0 -ui


#Boostrap other consuls
for i in $(seq 2 $NODES); do
  eval $(docker-machine env swarm-$i)
  docker run -d --net=host --name=consul \
    -e 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' \
    -e CONSUL=consul -e CONSUL_CHECK_LEADER=true \
    consul agent -server -bind=$(docker-machine ip swarm-$i) \
      -bootstrap-expect 3 -client=0.0.0.0 -ui \
      -join=$(docker-machine ip swarm-1)
done

for i in $(seq 1 $NODES); do
    eval $(docker-machine env swarm-$i)
    docker run -d \
        --name=registrator \
        --net=host \
        --volume=/var/run/docker.sock:/tmp/docker.sock \
        gliderlabs/registrator:latest \
          -internal consul://localhost:8500
done


#dnsmasq
sleep 10
for i in $(seq 1 $NODES); do
    eval $(docker-machine env swarm-$i)
    docker run -d --net=host --cap-add=NET_ADMIN --privileged --name=dnsmasq andyshinn/dnsmasq:2.76 --log-facility=- -S /consul/127.0.0.1#8600
done
